---
name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rust:1.72
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Init image
        run: ./ci/init.sh
      - name: Lint
        run: ./ci/lint.sh
      - name: Test
        run: ./ci/test.sh
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id:
          - debian-11
          - debian-12
          - ubuntu-20.04
          - ubuntu-22.04
    container:
      image: ${{ matrix.id }}:${{ matrix.version_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Init image
        run: ./ci/init-build.sh
      - name: Binaries
        run: ./ci/binaries.sh
      - name: Save binaries
        uses: actions/upload-artifact@v3
        with:
          name: libfirewall-${{ matrix.id }}
          path: libfirewall-${{ matrix.id }}.so
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    container:
      image: rust:1.72
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Init image
        run: ./ci/init-release.sh
      - name: Get binaries
        uses: actions/download-artifact@v3
        with:
          name: libfirewall-debian-11
      - name: Get binaries
        uses: actions/download-artifact@v3
        with:
          name: libfirewall-debian-12
      - name: Get binaries
        uses: actions/download-artifact@v3
        with:
          name: libfirewall-ubuntu-22.04
      - name: Get binaries
        uses: actions/download-artifact@v3
        with:
          name: libfirewall-ubuntu-20.04
      - name: Release
        run: ./ci/release.sh
